
eval "$(/opt/homebrew/bin/brew shellenv)"

#if [[ -o login && -o interactive && -t 1 && -z $TMUX ]] && command -v tmux >/dev/null 2>&1; then
#  exec tmux -u new -As main -c "$HOME/Desktop/code_heaven"
#fi